# Generated by Django 4.0 on 2023-02-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_news_text_de_news_text_fr_news_title_de_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title',
            new_name='title_en',
        ),
    ]
